# Generated by Django 3.0.3 on 2020-05-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Complete',
            new_name='complete',
        ),
    ]
